import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  documentationSidebar: [
    {
      type: 'doc',
      label: 'Home',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Data display',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Charts',
          collapsed: true,
          items: [
            'data-display/charts/index',
            {
              type: 'category',
              label: 'Analytics',
              collapsed: true,
              items: [
                'data-display/charts/analytics/bullet-chart',
                'data-display/charts/analytics/bump-chart',
                'data-display/charts/analytics/calendar-heatmap-chart',
                'data-display/charts/analytics/funnel-chart',
                'data-display/charts/analytics/heatmap-chart',
                'data-display/charts/analytics/kpi-card',
                'data-display/charts/analytics/matrix-chart',
                'data-display/charts/analytics/pictorial-bar-chart',
                'data-display/charts/analytics/pyramid-chart',
                'data-display/charts/analytics/slope-chart',
                'data-display/charts/analytics/table-chart',
                'data-display/charts/analytics/theme-river-chart',
                'data-display/charts/analytics/waffle-chart',
                'data-display/charts/analytics/word-cloud-chart',
              ],
            },
            {
              type: 'category',
              label: 'Bubble',
              collapsed: true,
              items: [
                'data-display/charts/bubble/bubble-chart',
                'data-display/charts/bubble/bubble-cloud-chart',
                'data-display/charts/bubble/packed-bubble-chart',
              ],
            },
            {
              type: 'category',
              label: 'Cartesian',
              collapsed: true,
              items: [
                'data-display/charts/cartesian/area-chart',
                'data-display/charts/cartesian/bar-chart',
                'data-display/charts/cartesian/combo-chart',
                'data-display/charts/cartesian/dot-plot-chart',
                'data-display/charts/cartesian/histogram-chart',
                'data-display/charts/cartesian/line-chart',
                'data-display/charts/cartesian/lollipop-chart',
                'data-display/charts/cartesian/pareto-chart',
                'data-display/charts/cartesian/range-area-chart',
                'data-display/charts/cartesian/range-bar-chart',
                'data-display/charts/cartesian/scatter-chart',
                'data-display/charts/cartesian/spline-area-chart',
                'data-display/charts/cartesian/spline-chart',
                'data-display/charts/cartesian/stacked-100-percent-bar-chart',
                'data-display/charts/cartesian/stacked-area-chart',
                'data-display/charts/cartesian/stacked-bar-chart',
                'data-display/charts/cartesian/step-line-chart',
                'data-display/charts/cartesian/variance-chart',
                'data-display/charts/cartesian/waterfall-chart',
              ],
            },
            {
              type: 'category',
              label: 'Circular',
              collapsed: true,
              items: [
                'data-display/charts/circular/donut-chart',
                'data-display/charts/circular/pie-chart',
                'data-display/charts/circular/semi-donut-chart',
              ],
            },
            {
              type: 'category',
              label: 'Comparison',
              collapsed: true,
              items: [
                'data-display/charts/comparison/diverging-bar-chart',
                'data-display/charts/comparison/dumbbell-chart',
                'data-display/charts/comparison/mekko-chart',
                'data-display/charts/comparison/mirror-bar-chart',
                'data-display/charts/comparison/parliament-chart',
                'data-display/charts/comparison/population-pyramid-chart',
                'data-display/charts/comparison/tornado-chart',
                'data-display/charts/comparison/venn-diagram-chart',
              ],
            },
            {
              type: 'category',
              label: 'Engineering',
              collapsed: true,
              items: [
                'data-display/charts/engineering/carpet-plot-chart',
                'data-display/charts/engineering/hexbin-chart',
                'data-display/charts/engineering/smith-chart',
                'data-display/charts/engineering/ternary-chart',
                'data-display/charts/engineering/wind-rose-chart',
              ],
            },
            {
              type: 'category',
              label: 'Financial',
              collapsed: true,
              items: [
                'data-display/charts/financial/candlestick-chart',
                'data-display/charts/financial/financial-chart',
                'data-display/charts/financial/heikin-ashi-chart',
                'data-display/charts/financial/hilo-chart',
                'data-display/charts/financial/kagi-chart',
                'data-display/charts/financial/ohlc-chart',
                'data-display/charts/financial/point-and-figure-chart',
                'data-display/charts/financial/renko-chart',
                'data-display/charts/financial/technical-indicators-chart',
              ],
            },
            {
              type: 'category',
              label: 'Gauges',
              collapsed: true,
              items: [
                'data-display/charts/gauges/circular-gauge-chart',
                'data-display/charts/gauges/gauge-chart',
                'data-display/charts/gauges/gradient-ring-chart',
                'data-display/charts/gauges/linear-gauge-chart',
                'data-display/charts/gauges/liquid-fill-gauge',
                'data-display/charts/gauges/progress-donut-chart',
              ],
            },
            {
              type: 'category',
              label: 'Hierarchy',
              collapsed: true,
              items: [
                'data-display/charts/hierarchy/alluvial-chart',
                'data-display/charts/hierarchy/arc-diagram-chart',
                'data-display/charts/hierarchy/chord-diagram',
                'data-display/charts/hierarchy/circle-packing-chart',
                'data-display/charts/hierarchy/dendrogram-chart',
                'data-display/charts/hierarchy/flame-graph',
                'data-display/charts/hierarchy/flow-chart',
                'data-display/charts/hierarchy/force-directed-graph',
                'data-display/charts/hierarchy/icicle-chart',
                'data-display/charts/hierarchy/indented-tree-chart',
                'data-display/charts/hierarchy/mindmap-chart',
                'data-display/charts/hierarchy/network-chart',
                'data-display/charts/hierarchy/organization-chart',
                'data-display/charts/hierarchy/process-flow-chart',
                'data-display/charts/hierarchy/radial-tree-chart',
                'data-display/charts/hierarchy/sankey-chart',
                'data-display/charts/hierarchy/sunburst-chart',
                'data-display/charts/hierarchy/treemap-chart',
              ],
            },
            {
              type: 'category',
              label: 'Maps',
              collapsed: true,
              items: [
                'data-display/charts/maps/bubble-map-chart',
                'data-display/charts/maps/choropleth-map-chart',
                'data-display/charts/maps/heatmap-map-chart',
                'data-display/charts/maps/seat-map-chart',
                'data-display/charts/maps/shape-map-chart',
              ],
            },
            {
              type: 'category',
              label: 'Radial',
              collapsed: true,
              items: [
                'data-display/charts/radial/nightingale-rose-chart',
                'data-display/charts/radial/polar-area-chart',
                'data-display/charts/radial/polar-chart',
                'data-display/charts/radial/radar-chart',
                'data-display/charts/radial/radial-bar-chart',
                'data-display/charts/radial/radial-line-chart',
              ],
            },
            {
              type: 'category',
              label: 'Scheduling',
              collapsed: true,
              items: [
                'data-display/charts/scheduling/gantt-chart',
                'data-display/charts/scheduling/sparkline-chart',
                'data-display/charts/scheduling/spiral-timeline-chart',
                'data-display/charts/scheduling/swimlane-chart',
                'data-display/charts/scheduling/timeline-chart',
              ],
            },
            {
              type: 'category',
              label: 'Shared elements',
              collapsed: true,
              items: [
                'data-display/charts/shared-elements/annotations-chart',
                'data-display/charts/shared-elements/axis-customization-chart',
                'data-display/charts/shared-elements/crosshairs-chart',
                'data-display/charts/shared-elements/data-labels-chart',
                'data-display/charts/shared-elements/export-chart',
                'data-display/charts/shared-elements/interactions-chart',
                'data-display/charts/shared-elements/legend-chart',
                'data-display/charts/shared-elements/markers-chart',
                'data-display/charts/shared-elements/tooltip-chart',
                'data-display/charts/shared-elements/trendline-chart',
              ],
            },
            {
              type: 'category',
              label: 'Statistical',
              collapsed: true,
              items: [
                'data-display/charts/statistical/beeswarm-plot-chart',
                'data-display/charts/statistical/boxplot-chart',
                'data-display/charts/statistical/contour-plot-chart',
                'data-display/charts/statistical/density-plot-chart',
                'data-display/charts/statistical/error-bar-chart',
                'data-display/charts/statistical/mosaic-chart',
                'data-display/charts/statistical/parallel-coordinates-chart',
                'data-display/charts/statistical/ridgeline-chart',
                'data-display/charts/statistical/strip-plot-chart',
                'data-display/charts/statistical/violin-plot-chart',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Collections',
          collapsed: true,
          items:[
              'data-display/collections/carousel',
              'data-display/collections/itemscontrol',
              'data-display/collections/itemsrepeater',
              'data-display/collections/listbox',
          ],
        },
        'data-display/contentcontrol',
        {
          type: 'category',
          label: 'Structured data',
          collapsed: true,
          items:[
              'data-display/structured-data/datagrid',
              {
                type: 'category',
                label: 'TreeDataGrid',
                collapsed: true,
                items: [
                  'data-display/structured-data/treedatagrid/index',
                  'data-display/structured-data/treedatagrid/column-types',
                  'data-display/structured-data/treedatagrid/selection-modes',
                  'data-display/structured-data/treedatagrid/expand-and-collapse',
                  'data-display/structured-data/treedatagrid/sorting',
                  'data-display/structured-data/treedatagrid/filtering',
                  'data-display/structured-data/treedatagrid/breaking-changes-v12',
                ],
              },
              'data-display/structured-data/treeview',
          ],
        },
        {
          type: 'category',
          label: 'Text display',
          collapsed: true,
          items:[
              'data-display/text-display/label',
              {
                type: 'category',
                label: 'Markdown',
                collapsed: true,
                items: [
                  'data-display/text-display/markdown/index',
                  'data-display/text-display/markdown/markdown-styling',
                  'data-display/text-display/markdown/codehighlighter',
                  'data-display/text-display/markdown/imageloader',
                ],
              },
              'data-display/text-display/selectabletextblock',
              {
                type: 'category',
                label: 'TextBlock',
                link: {
                  type: 'doc',
                  id: 'data-display/text-display/textblock',
                },
                items: [
                  'data-display/text-display/texttrimming',
                ],
              },
          ],
        },
        'data-display/transitioningcontentcontrol',
      ],
    },
    {
      type: 'category',
      label: 'Feedback',
      collapsed: true,
      items:[
        'feedback/notification',
        'feedback/popup',
        'feedback/progressbar',
        'feedback/tooltip',
      ],
    },
    {
      type: 'category',
      label: 'Input',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Buttons',
          collapsed: true,
          items:[
              'input/buttons/button',
              'input/buttons/buttonspinner',
              'input/buttons/hyperlinkbutton',
              'input/buttons/radiobutton',
              'input/buttons/repeatbutton',
              'input/buttons/splitbutton',
              'input/buttons/togglebutton',
              'input/buttons/togglesplitbutton',
          ],
        },
        {
          type: 'category',
          label: 'Date and time',
          collapsed: true,
          items:[
            'input/date-and-time/calendar',
            'input/date-and-time/calendardatepicker',
            'input/date-and-time/datepicker',
            'input/date-and-time/timepicker',
          ],
        },
        {
          type: 'category',
          label: 'Selectors',
          collapsed: true,
          items:[
              'input/selectors/checkbox',
              'input/selectors/colorpicker',
              'input/selectors/colorview',
              'input/selectors/combobox',
              'input/selectors/numericupdown',
              'input/selectors/slider',
              'input/selectors/toggleswitch',
          ],
        },
        {
          type: 'category',
          label: 'Text input',
          collapsed: true,
          items:[
              'input/text-input/autocompletebox',
              'input/text-input/maskedtextbox',
              'input/text-input/textbox',
              {
                type: 'category',
                label: 'RichTextEditor',
                collapsed: true,
                items: [
                  'input/text-input/richtexteditor/index',
                  'input/text-input/richtexteditor/document-viewer',
                  'input/text-input/richtexteditor/toolbar',
                  'input/text-input/richtexteditor/extension-patterns',
                  'input/text-input/richtexteditor/performance-tuning',
                  'input/text-input/richtexteditor/thread-safety',
                ],
              },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Layout',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Containers',
          collapsed: true,
          items:[
              'layout/containers/border',
              'layout/containers/expander',
              'layout/containers/flyout',
              'layout/containers/groupbox',
              'layout/containers/refreshcontainer',
              'layout/containers/scrollviewer',
              'layout/containers/splitview',
              'layout/containers/viewbox',
              {
                type: 'category',
                label: 'Virtual keyboard',
                collapsed: true,
                items: [
                  'input/text-input/virtualkeyboard/index',
                  'input/text-input/virtualkeyboard/virtualkeyboard-control',
                  'input/text-input/virtualkeyboard/virtualkeyboardscope',
                ],
              },
          ],
        },
        'layout/decorator',
        'layout/layouttransformcontrol',
        {
          type: 'category',
          label: 'Panels',
          collapsed: true,
          items:[
              'layout/panels/canvas',
              'layout/panels/dockpanel',
              'layout/panels/grid',
              'layout/panels/gridsplitter',
              'layout/panels/panel',
              'layout/panels/relativepanel',
              'layout/panels/stackpanel',
              'layout/panels/uniformgrid',
              'layout/panels/wrappanel',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Media',
      collapsed: true,
      items:[
        'media/drawingimage',
        'media/image',
        {
          type: 'category',
          label: 'MediaPlayer',
          collapsed: true,
          items: [
            'media/mediaplayer/index',
            'media/mediaplayer/mediasource',
            'media/mediaplayer/mediaplayer-class',
            'media/mediaplayer/media-playback',
          ],
        },
        'media/pathicon',
      ],
    },
    {
      type: 'category',
      label: 'Menus',
      collapsed: true,
      items:[
        'menus/contextmenu',
        'menus/menu',
        'menus/menuflyout',
        'menus/nativemenu',
        'menus/separator',
      ],
    },
    {
      type: 'category',
      label: 'Navigation',
      collapsed: true,
      items:[
        'navigation/commandbar',
        'navigation/contentpage',
        'navigation/drawerpage',
        'navigation/navigationpage',
        'navigation/tabbedpage',
        'navigation/tabcontrol',
        'navigation/tabstrip',
      ],
    },
    {
      type: 'category',
      label: 'Primitives',
      collapsed: true,
      items:[
        'primitives/scrollbar',
        'primitives/themevariantscope',
        'primitives/usercontrol',
      ],
    },
    {
      type: 'category',
      label: 'System',
      collapsed: true,
      items:[
        'navigation/trayicon',
        'primitives/window',
        'primitives/windowdrawndecorations',
      ],
    },
    {
      type: 'category',
      label: 'Web',
      collapsed: true,
      items:[
        'web/nativewebdialog',
        {
          type: 'category',
          label: 'NativeWebView',
          link: {
            type: 'doc',
            id: 'web/nativewebview',
          },
          items: [
            'web/webview-environment',
            'web/webauthenticationbroker',
          ],
        },
      ],
    }
  ],
};

export default sidebars;
