/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  documentationSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'documentation/getting-started/index'},
      items: [ {
                  type: 'category',
                  label: 'IDE Support',
                  link: {type: 'doc', id: 'documentation/getting-started/ide-support/index'},
                  items: ['documentation/getting-started/ide-support/jetbrains-rider-setup'],
                },
                {
                  type: 'category',
                  label: 'Programming with Avalonia',
                  link: {type: 'doc', id: 'documentation/getting-started/programming-with-avalonia/index'},
                  items: ['documentation/getting-started/programming-with-avalonia/the-model-view-viewmodel-pattern-mvvm', 
                          'documentation/getting-started/programming-with-avalonia/controls-and-layouts',
                          'documentation/getting-started/programming-with-avalonia/data-binding',
                          'documentation/getting-started/programming-with-avalonia/graphics-and-animations'],
                },              
              'documentation/getting-started/windows',
              'documentation/getting-started/usercontrols',
              'documentation/getting-started/assets',
              'documentation/getting-started/developer-tools',
              'documentation/getting-started/logging-errors-and-warnings',
              'documentation/getting-started/UnhandledExceptions',
              'documentation/getting-started/application-lifetimes'],
    },
    {
      type: 'category',
      label: 'Data Binding',
      link: {type: 'doc', id: 'documentation/data-binding/index'},
      items: ['documentation/data-binding/the-datacontext',
              'documentation/data-binding/change-notifications',
              'documentation/data-binding/bindings',
              'documentation/data-binding/binding-classes'],
    },
    {
      type: 'category',
      label: 'Animations',
      link: {type: 'doc', id: 'documentation/animations/index'},
      items: ['documentation/animations/keyframe-animations',
              'documentation/animations/transitions',
              'documentation/animations/pageTransitions'
              ],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Avalonia.Animations',
      link: {type: 'doc', id: 'api/Avalonia-Animation/Animators'},
      items: [
              ],
    },
  ],
  guideSidebar: [
    {
      type: 'category',
      label: 'Basics',
      items: ['guides/basics/introduction-to-xaml',
              'guides/basics/code-behind',
              'guides/basics/mvvm',
              'guides/basics/accessing-the-ui-thread',
              ],
    },
    {
      type: 'category',
      label: 'Deep Dives',
      items: ['guides/deep-dives/running-on-raspbian-lite-via-drm',
              'guides/deep-dives/running-your-app-on-a-raspberry-pi'           
              ],
    },    
  ],  
   
};

module.exports = sidebars;
