import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  documentationSidebar: [
    'welcome',
    'supported-platforms',
    {
      'type': 'category',
      'label': 'Getting started',
      'link': {
        'type': 'doc',
        'id': 'get-started/index',
      },
      'items': [
        {
          'type': 'category',
          'label': 'Starter tutorial',
          'link' : {
            'type' : 'doc',
            'id': 'get-started/starter-tutorial/index'
          },
          'items': [
            'get-started/starter-tutorial/adding-a-control',
            'get-started/starter-tutorial/adding-some-layout',
            'get-started/starter-tutorial/customizing-the-avalonia-window',
            'get-started/starter-tutorial/establishing-events-and-responses',
            'get-started/starter-tutorial/converting-data',
            'get-started/starter-tutorial/exercises',
          ],
        },
      ],
    },
    {
      'type': 'category',
      'label': 'Tutorials',
      'link': {
        'type': 'doc',
        'id': 'tutorials/index',
      },
      'items': [
        {'type': 'link',
         'label': 'Starter tutorial',
         'href': 'https://docs.avaloniaui.net/docs/get-started/starter-tutorial',
        },
        {
          'type': 'link',
          'label': 'ToDo List App',
          'href': 'https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CompleteApps/SimpleToDoList' ,
        },
        {
          'type': 'link',
          'label': 'Music Store App',
          'href': 'https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CompleteApps/Avalonia.MusicStore',
        },
      ],
    },
    {
      'type': 'category',
      'label': 'App development',
       'collapsed': true,
      'items': [
        'app-development/cross-platform-solution-setup',
        'app-development/dependency-injection',
        'app-development/localizing',
        'app-development/logging-errors-and-warnings',
        {
          'type': 'category',
          'label': 'ReactiveUI',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'app-development/reactiveui'},],
         },
      ],
    },
    {
      'type': 'category',
      'label': 'UI development',
      'collapsed': true,
      'items': [
        'ui-development/adding-interactivity',
        {
          'type': 'category',
          'label': 'Custom controls',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'ui-development/custom-controls'},],
        },
        {
          'type': 'category',
          'label': 'Graphics',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'ui-development/graphics'},],
        },
        'ui-development/preview-and-design-time',
        {
          'type': 'category',
          'label': 'Styling',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'ui-development/styling'},],
        },
        'ui-development/resource-dictionary',
      ],
    },
    {
      'type': 'category',
      'label': 'Development optimization',
      'collapsed': true,
      'items': [{'type': 'autogenerated', 'dirName': 'development-optimization'},],
    },
    {
      'type': 'category',
      'label': 'Data',
      'collapsed': true,
      'items': [
        'data/binding-classes',
        'data/binding-from-code',
        'data/binding-to-controls',
        'data/data-validation',
        'data/how-to-bind-can-execute',
        'data/how-to-bind-image-files',
        'data/how-to-bind-multiple-properties',
        'data/how-to-bind-tabs',
        'data/how-to-bind-to-a-collection',
        'data/how-to-bind-to-a-task-result',
        'data/how-to-bind-to-an-observable',
        'data/how-to-create-a-custom-data-binding-converter',
        'data/inotifypropertychanged',
        {
          'type': 'category',
          'label': 'Data templates',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'data/data-templates'},],
        },
      ],
    },
    {
      'type': 'category',
      'label': 'Platform-specific guides',
      'collapsed': true,
      'items': [
        {
          'type': 'category',
          'label': 'Android',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'platform-specific-guides/android'},],
        },
        'platform-specific-guides/dotnet',
        'platform-specific-guides/ios',
        'platform-specific-guides/linux',
        'platform-specific-guides/macos',
        'platform-specific-guides/multi-touch-events',
        'platform-specific-guides/raspberry-pi',
        'platform-specific-guides/webassembly',
        'platform-specific-guides/winforms',
        'platform-specific-guides/xaml'
      ],
    },
    {
      'type': 'category',
      'label': 'Migration',
       'collapsed': true,
      'items': [
        {
          'type': 'category',
          'label': 'WPF',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'migration/wpf'},],
        },
      ],
    },
    {
      'type': 'category',
      'label': 'Deep Dives',
      'link': {
        'type': 'doc',
        'id': 'concepts/index',
      },
      'items': [
        {
          'type': 'category',
          'label': 'Headless Platform',
          'link': {
            'type': 'doc',
            'id': 'concepts/headless/index',
          },
          'items': [
            'concepts/headless/headless-xunit',
            'concepts/headless/headless-nunit',
            'concepts/headless/headless-custom',
          ],
        },
        {
          'type': 'category',
          'label': 'Input',
          'link': {
            'type': 'doc',
            'id': 'concepts/input/index',
          },
          'items': [
            'concepts/input/routed-events',
            'concepts/input/pointer',
            'concepts/input/focus',
            'concepts/input/gestures',
            'concepts/input/hotkeys',
            'concepts/input/binding-key-and-mouse',
          ],
        },
        'concepts/the-main-window',
        {
          'type': 'category',
          'label': 'The MVVM Pattern',
          'link': {
            'type': 'doc',
            'id': 'concepts/the-mvvm-pattern/index',
          },
          'items': [
            'concepts/the-mvvm-pattern/avalonia-ui-and-mvvm',
          ],
        },
        {
          'type': 'category',
          'label': 'Markup extensions',
          'link': {
            'type': 'doc',
            'id': 'concepts/markupextensions/index',
          },
          'items': [
            'concepts/markupextensions/options-markup-extensions',
          ],
        },
        {
          'type': 'category',
          'label': 'ReactiveUI',
          'link': {
            'type': 'doc',
            'id': 'concepts/reactiveui/index',
          },
          'items': [
            'concepts/reactiveui/reactive-view-model',
            'concepts/reactiveui/command-update',
            'concepts/reactiveui/reactive-command',
            'concepts/reactiveui/view-activation',
            'concepts/reactiveui/routing',
            'concepts/reactiveui/data-persistence',
            'concepts/reactiveui/binding-to-sorted-filtered-list',
          ],
        },
        {
          'type': 'category',
          'label': 'Services',
          'link': {
            'type': 'doc',
            'id': 'concepts/services/index',
          },
          'items': [
            'concepts/services/activatable-lifetime',
            'concepts/services/clipboard',
            'concepts/services/launcher',
            'concepts/services/focus-manager',
            'concepts/services/input-pane',
            'concepts/services/insets-manager',
            'concepts/services/platform-settings',
            {
              'type': 'category',
              'label': 'Storage Provider',
              'link': {
                'type': 'doc',
                'id': 'concepts/services/storage-provider/index',
              },
              'items': [
                'concepts/services/storage-provider/storage-item',
                'concepts/services/storage-provider/bookmarks',
                'concepts/services/storage-provider/file-picker-options',
              ],
            },
              ],
        },
        'concepts/image-interpolation',
        'concepts/blend-modes',
        'concepts/templated-controls',
        'concepts/ui-composition',
        'concepts/unhandledexceptions',
        'concepts/toplevel'
      ],
    },
    {
      'type': 'category',
      'label': 'Deployment',
      'collapsed': true,
      'items': [
        'deployment/native-aot',
      ],
    },
    'faq',
    'community',
    {
      type: 'link',
      label: 'Release notes',
      href: 'https://github.com/AvaloniaUI/Avalonia/releases',
    },
    {
      type: 'link',
      label: 'API Reference',
      href: 'https://api-docs.avaloniaui.net/docs/category/avalonia',
    },
  ],
};

export default sidebars;
