import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  documentationSidebar: [
    'welcome',
    'supported-platforms',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'get-started/index',
      },
      items: [
        {
          type: 'category',
          label: 'Starter Tutorial',
          link: {
            type: 'doc',
            id: 'get-started/starter-tutorial/index',
          },
          items: [
            'get-started/starter-tutorial/adding-a-control',
            'get-started/starter-tutorial/adding-some-layout',
            'get-started/starter-tutorial/customizing-the-avalonia-window',
            'get-started/starter-tutorial/establishing-events-and-responses',
            'get-started/starter-tutorial/converting-data',
            'get-started/starter-tutorial/exercises',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Fundamentals',
      collapsed: true,
      items: [
        'fundamentals/avalonia-xaml',
        'fundamentals/code-behind',
        'fundamentals/main-window',
        'fundamentals/top-level',
        'fundamentals/ui-composition',
        'fundamentals/cross-platform-architecture',
        'fundamentals/the-mvvm-pattern',
        'fundamentals/application-lifetimes',
        'fundamentals/assets',
      ],
    },
    {
      type: 'category',
      label: 'Data Binding',
      collapsed: true,
      items: [
        'data-binding/introduction-to-data-binding',
        'data-binding/data-binding-syntax',
        'data-binding/data-context',
        'data-binding/compiled-bindings',
        'data-binding/markup-extensions',
        'data-binding/binding-from-code',
        'data-binding/binding-to-controls',
        'data-binding/binding-classes',
        'data-binding/inotifypropertychanged',
        'data-binding/how-to-bind-to-a-collection',
        'data-binding/how-to-bind-multiple-properties',
        'data-binding/how-to-bind-to-a-task-result',
        'data-binding/how-to-bind-to-an-observable',
        'data-binding/how-to-bind-image-files',
        'data-binding/how-to-bind-tabs',
        'data-binding/how-to-bind-can-execute',
        'data-binding/how-to-create-a-custom-data-binding-converter',
        'data-binding/built-in-data-binding-converters',
      ],
    },
    {
      type: 'category',
      label: 'Data Templates',
      collapsed: true,
      items: [
        'data-templates/introduction-to-data-templates',
        'data-templates/control-content',
        'data-templates/content-templates',
        'data-templates/data-template-collection',
        'data-templates/creating-data-templates-in-code',
        'data-templates/reusing-data-templates',
        'data-templates/view-locator',
      ],
    },
    {
      type: 'category',
      label: 'Styling',
      collapsed: true,
      items: [
        'styling/styles',
        'styling/style-classes',
        'styling/control-themes',
        'styling/themes',
        'styling/container-queries',
        'styling/custom-fonts',
        'styling/sharing-styles',
        'styling/theme-variants',
        'styling/style-selectors',
        'styling/style-selector-syntax',
        'styling/property-setters',
        'styling/pseudoclasses',
      ],
    },
    {
      type: 'category',
      label: 'Layout',
      collapsed: true,
      items: [
        'layout/layout',
        'layout/positioning-controls',
      ],
    },
    {
      type: 'category',
      label: 'Input & Interaction',
      collapsed: true,
      items: [
        'input-interaction/pointer',
        'input-interaction/focus',
        'input-interaction/gestures',
        'input-interaction/keyboard-and-hotkeys',
        'input-interaction/routed-events',
        'input-interaction/adding-interactivity',
        'input-interaction/mouse-and-keyboard-shortcuts',
        {
          type: 'category',
          label: 'Gesture Recognizers',
          collapsed: true,
          items: [
            'input-interaction/gestures/pinch-gesture-recognizer',
            'input-interaction/gestures/pull-gesture-recognizer',
            'input-interaction/gestures/scroll-gesture-recognizer',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Graphics & Animation',
      collapsed: true,
      items: [
        'graphics-animation/animations',
        'graphics-animation/animation-settings',
        'graphics-animation/keyframe-animations',
        'graphics-animation/control-transitions',
        'graphics-animation/page-transitions',
        'graphics-animation/drawing-graphics',
        'graphics-animation/gradients',
        'graphics-animation/adding-icons',
        'graphics-animation/image-interpolation',
        'graphics-animation/bitmap-blend-modes',
      ],
    },
    {
      type: 'category',
      label: 'Custom Controls',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'custom-controls/index',
      },
      items: [
        'custom-controls/choosing-a-custom-control-type',
        'custom-controls/custom-control-class',
        'custom-controls/templated-controls',
        'custom-controls/drawing-custom-controls',
        'custom-controls/defining-properties',
        'custom-controls/defining-events',
        'custom-controls/attached-properties',
        'custom-controls/control-trees',
        'custom-controls/custom-flyout',
        'custom-controls/custom-itemspanel',
        'custom-controls/custom-panel',
        'custom-controls/custom-control-library',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      collapsed: true,
      items: [
        'services/clipboard',
        'services/file-dialogs',
        'services/focus-manager',
        'services/input-pane',
        'services/insets-manager',
        'services/launcher',
        'services/platform-settings',
        'services/activatable-lifetime',
        {
          type: 'category',
          label: 'Storage',
          collapsed: true,
          items: [
            'services/storage/storage-provider',
            'services/storage/storage-item',
            'services/storage/bookmarks',
            'services/storage/file-picker-options',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'App Development',
      collapsed: true,
      items: [
        'app-development/cross-platform-solution-setup',
        'app-development/dependency-injection',
        'app-development/localizing',
        'app-development/embedding-web-content',
        'app-development/logging-errors-and-warnings',
        'app-development/setting-unhandled-exceptions',
        'app-development/resource-dictionary',
        'app-development/rendering-markdown',
        'app-development/xaml-preview-and-design-settings',
        'app-development/data-validation',
        'app-development/accessing-the-ui-thread',
        {
          type: 'category',
          label: 'ReactiveUI',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'app-development/reactiveui' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Integration',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Android',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'platform-specific-guides/android' }],
        },
        'platform-specific-guides/ios',
        'platform-specific-guides/macos',
        'platform-specific-guides/webassembly',
        'platform-specific-guides/dotnet',
        'platform-specific-guides/windows',
        'platform-specific-guides/raspberry-pi',
        'platform-specific-guides/xaml',
        'platform-specific-guides/multi-touch-events',
        'platform-specific-guides/virtual-keyboard',
      ],
    },
    {
      type: 'category',
      label: 'Media',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'media' }],
    },
    {
      type: 'category',
      label: 'Testing',
      collapsed: true,
      items: [
        'testing/setting-up-the-headless-platform',
        'testing/headless-xunit',
        'testing/headless-nunit',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: true,
      items: [
        'deployment/android',
        'deployment/ios',
        'deployment/macos',
        'deployment/linux',
        'deployment/webassembly',
        'deployment/native-aot',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'WPF',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'migration/wpf' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Samples & Tutorials',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'samples-tutorials/index',
      },
      items: [
        {
          type: 'link',
          label: 'Starter Tutorial',
          href: '/docs/get-started/starter-tutorial',
        },
        {
          type: 'link',
          label: 'ToDo List App',
          href: 'https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CompleteApps/SimpleToDoList',
        },
        {
          type: 'link',
          label: 'Music Store App',
          href: 'https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CompleteApps/Avalonia.MusicStore',
        },
      ],
    },
    'avalonia12-breaking-changes',
    'faq',
    'community',
  ],
};

export default sidebars;
