import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  documentationSidebar: [
    'welcome',
    'supported-platforms',
    {
      'type': 'category',
      'label': 'Getting started',
      'link': {
        'type': 'doc',
        'id': 'get-started/index',
      },
      'items': [
        {
          'type': 'category',
          'label': 'Starter tutorial',
          'link' : {
            'type' : 'doc',
            'id': 'get-started/starter-tutorial/index'
          },
          'items': [
            'get-started/starter-tutorial/adding-a-control',
            'get-started/starter-tutorial/adding-some-layout',
            'get-started/starter-tutorial/customizing-the-avalonia-window',
            'get-started/starter-tutorial/establishing-events-and-responses',
            'get-started/starter-tutorial/converting-data',
            'get-started/starter-tutorial/exercises',
          ],
        },
      ],
    },
    {
      'type': 'category',
      'label': 'Tutorials',
      'link': {
        'type': 'doc',
        'id': 'tutorials/index',
      },
      'items': [
        {'type': 'link',
         'label': 'Starter tutorial',
         'href': 'https://docs.avaloniaui.net/docs/get-started/starter-tutorial',
        },
        {
          'type': 'link',
          'label': 'ToDo List App',
          'href': 'https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CompleteApps/SimpleToDoList' ,
        },
        {
          'type': 'link',
          'label': 'Music Store App',
          'href': 'https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CompleteApps/Avalonia.MusicStore',
        },
      ],
    },
    {
      'type': 'category',
      'label': 'App development',
       'collapsed': true,
      'items': [
        'app-development/cross-platform-solution-setup',
        'app-development/dependency-injection',
        'app-development/localizing',
        'app-development/logging-errors-and-warnings',
        {
          'type': 'category',
          'label': 'ReactiveUI',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'app-development/reactiveui'},],
         },
        'app-development/setting-unhandled-exceptions',
      ],
    },
    {
      'type': 'category',
      'label': 'UI development',
      'collapsed': true,
      'items': [
        'ui-development/adding-interactivity',
        {
          'type': 'category',
          'label': 'Custom controls',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'ui-development/custom-controls'},],
        },
        {
          'type': 'category',
          'label': 'Graphics',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'ui-development/graphics'},],
        },
        'ui-development/mouse-and-keyboard-shortcuts',
        'ui-development/preview-and-design-time',
        {
          'type': 'category',
          'label': 'Styling',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'ui-development/styling'},],
        },
        'ui-development/resource-dictionary',
      ],
    },
    {
      'type': 'category',
      'label': 'Development optimization',
      'collapsed': true,
      'items': [
        {
          type: 'category',
          label: 'Avalonia Accelerate',
          collapsed: true,
          items: [
              'development-optimization/accelerate-tools/installing-accelerate',
          ],
        },
        'development-optimization/accessing-the-ui-thread',
        'development-optimization/legacy-developer-tools',
      ],
    },
    {
      'type': 'category',
      'label': 'Data',
      'collapsed': true,
      'items': [
        'data/binding-classes',
        'data/binding-from-code',
        'data/binding-to-controls',
        'data/data-validation',
        'data/how-to-bind-can-execute',
        'data/how-to-bind-image-files',
        'data/how-to-bind-multiple-properties',
        'data/how-to-bind-tabs',
        'data/how-to-bind-to-a-collection',
        'data/how-to-bind-to-a-task-result',
        'data/how-to-bind-to-an-observable',
        'data/how-to-create-a-custom-data-binding-converter',
        'data/inotifypropertychanged',
        {
          'type': 'category',
          'label': 'Data templates',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'data/data-templates'},],
        },
      ],
    },
    {
      'type': 'category',
      'label': 'Platform-specific guides',
      'collapsed': true,
      'items': [
        {
          'type': 'category',
          'label': 'Android',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'platform-specific-guides/android'},],
        },
        'platform-specific-guides/dotnet',
        'platform-specific-guides/ios',
        'platform-specific-guides/linux',
        'platform-specific-guides/macos',
        'platform-specific-guides/multi-touch-events',
        'platform-specific-guides/raspberry-pi',
        'platform-specific-guides/webassembly',
        'platform-specific-guides/winforms',
        'platform-specific-guides/xaml'
      ],
    },
    {
      'type': 'category',
      'label': 'Media',
      'collapsed': true,
      'items': [{'type': 'autogenerated', 'dirName': 'media'},],
    },
    {
      'type': 'category',
      'label': 'Migration',
       'collapsed': true,
      'items': [
        {
          'type': 'category',
          'label': 'WPF',
          'collapsed': true,
          'items': [{'type': 'autogenerated', 'dirName': 'migration/wpf'},],
        },
      ],
    },
    {
      'type': 'category',
      'label': 'Testing',
       'collapsed': true,
      'items': [
        'testing/setting-up-the-headless-platform',
        'testing/headless-xunit',
        'testing/headless-nunit',
      ],
    },
    {
      'type': 'category',
      'label': 'Deployment',
      'collapsed': true,
      'items': [
        'deployment/native-aot',
      ],
    },
    'faq',
    'community',
    {
      type: 'link',
      label: 'Release notes',
      href: 'https://github.com/AvaloniaUI/Avalonia/releases',
    },
    {
      type: 'link',
      label: 'API Reference',
      href: 'https://api-docs.avaloniaui.net/docs/category/avalonia',
    },
  ],
};

export default sidebars;
