name: Link checker

on:
  schedule:
    - cron: '0 8 * * 1' # Runs every Monday at 8:00 AM UTC
  workflow_dispatch:
  repository_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      issues: write # required for peter-evans/create-issue-from-file
    steps:
        - uses: actions/checkout@v4

        - name: Check links with lychee
          id: lychee
          uses: lycheeverse/lychee-action@v2
          with:
            args: >-
                --verbose
                --no-progress
                --timeout 30
                --max-retries 3
                --cache
                --max-cache-age 1d
                --accept 200..=206,302,304,403,429
                --base-url https://docs.avaloniaui.net
                --exclude-path 'api'
                --exclude-path '.claude'
                --exclude-path 'README.md'
                --exclude 'https://xpf-nuget-feed.avaloniaui.net/'
                --exclude 'https://xpf-nuget-feed.avaloniaui.net/packages/xpf.sdk'
                --exclude 'https://xpf-nuget-feed.avaloniaui.net/v3/index.json'
                --exclude 'https://github.com/AvaloniaUIOU/CalculatorDemo'
                './**/*.md'
                './**/*.mdx'
            format: markdown
            output: ./lychee/results.md
            token: ${{ secrets.GITHUB_TOKEN }}
            fail: false # so lychee doesn't abort the job
            jobSummary: true
      
        - name: Create issue from link checker results
          if: steps.lychee.outputs.exit_code != 0
          uses: peter-evans/create-issue-from-file@v6
          with:
            title: Link checker found broken links
            content-filepath: ./lychee/results.md
            labels: 'link-checker'